admin_agency_labels = ["Army and Air Force Exchange Service", 
                       "Atomic Energy Commission", 
                       "Secretary or administrative unit or personnel of the U.S. Air Force", 
                       "Department or Secretary of Agriculture", 
                       "Alien Property Custodian", 
                       "Secretary or administrative unit or personnel of the U.S. Army", 
                       "Board of Immigration Appeals", 
                       "Bureau of Indian Affairs", 
                       "Bureau of Prisons", 
                       "Bonneville Power Administration", 
                       "Benefits Review Board", 
                       "Civil Aeronautics Board", 
                       "Bureau of the Census", 
                       "Central Intelligence Agency", 
                       "Commodity Futures Trading Commission", 
                       "Department or Secretary of Commerce", 
                       "Comptroller of Currency", 
                       "Consumer Product Safety Commission", 
                       "Civil Rights Commission", 
                       "Civil Service Commission, U.S.", 
                       "Customs Service or Commissioner or Collector of Customs", 
                       "Defense Base Closure and REalignment Commission", 
                       "Drug Enforcement Agency", 
                       "Department or Secretary of Defense (and Department or Secretary of War)", 
                       "Department or Secretary of Energy", 
                       "Department or Secretary of the Interior", 
                       "Department of Justice or Attorney General", 
                       "Department or Secretary of State", 
                       "Department or Secretary of Transportation", 
                       "Department or Secretary of Education", 
                       "U.S. Employees' Compensation Commission, or Commissioner", 
                       "Equal Employment Opportunity Commission", 
                       "Environmental Protection Agency or Administrator", 
                       "Federal Aviation Agency or Administration", 
                       "Federal Bureau of Investigation or Director", 
                       "Federal Bureau of Prisons", 
                       "Farm Credit Administration", 
                       "Federal Communications Commission (including a predecessor, Federal Radio Commission)", 
                       "Federal Credit Union Administration", 
                       "Food and Drug Administration", 
                       "Federal Deposit Insurance Corporation", 
                       "Federal Energy Administration", 
                       "Federal Election Commission", 
                       "Federal Energy Regulatory Commission", 
                       "Federal Housing Administration", 
                       "Federal Home Loan Bank Board", 
                       "Federal Labor Relations Authority", 
                       "Federal Maritime Board", 
                       "Federal Maritime Commission", 
                       "Farmers Home Administration", 
                       "Federal Parole Board", 
                       "Federal Power Commission", 
                       "Federal Railroad Administration", 
                       "Federal Reserve Board of Governors", 
                       "Federal Reserve System", 
                       "Federal Savings and Loan Insurance Corporation", 
                       "Federal Trade Commission", 
                       "Federal Works Administration, or Administrator", 
                       "General Accounting Office", 
                       "Comptroller General", 
                       "General Services Administration", 
                       "Department or Secretary of Health, Education and Welfare", 
                       "Department or Secretary of Health and Human Services", 
                       "Department or Secretary of Housing and Urban Development", 
                       "Administrative agency established under an interstate compact (except for the MTC)", 
                       "Interstate Commerce Commission", 
                       "Indian Claims Commission", 
                       "Immigration and Naturalization Service, or Director of, or District Director of, or Immigration and Naturalization Enforcement", 
                       "Internal Revenue Service, Collector, Commissioner, or District Director of", 
                       "Information Security Oversight Office", 
                       "Department or Secretary of Labor", 
                       "Loyalty Review Board", 
                       "Legal Services Corporation", 
                       "Merit Systems Protection Board", 
                       "Multistate Tax Commission", 
                       "National Aeronautics and Space Administration", 
                       "Secretary or administrative unit or personnel of the U.S. Navy", 
                       "National Credit Union Administration", 
                       "National Endowment for the Arts", 
                       "National Enforcement Commission", 
                       "National Highway Traffic Safety Administration", 
                       "National Labor Relations Board, or regional office or officer", 
                       "National Mediation Board", 
                       "National Railroad Adjustment Board", 
                       "Nuclear Regulatory Commission", 
                       "National Security Agency", 
                       "Office of Economic Opportunity", 
                       "Office of Management and Budget", 
                       "Office of Price Administration, or Price Administrator", 
                       "Office of Personnel Management", 
                       "Occupational Safety and Health Administration", 
                       "Occupational Safety and Health Review Commission", 
                       "Office of Workers' Compensation Programs", 
                       "Patent Office, or Commissioner of, or Board of Appeals of", 
                       "Pay Board (established under the Economic Stabilization Act of 1970)", 
                       "Pension Benefit Guaranty Corporation", 
                       "U.S. Public Health Service", 
                       "Postal Rate Commission", 
                       "Provider Reimbursement Review Board", 
                       "Renegotiation Board", 
                       "Railroad Adjustment Board", 
                       "Railroad Retirement Board", 
                       "Subversive Activities Control Board", 
                       "Small Business Administration", 
                       "Securities and Exchange Commission", 
                       "Social Security Administration or Commissioner", 
                       "Selective Service System", 
                       "Department or Secretary of the Treasury", 
                       "Tennessee Valley Authority", 
                       "United States Forest Service", 
                       "United States Parole Commission", 
                       "Postal Service and Post Office, or Postmaster General, or Postmaster", 
                       "United States Sentencing Commission", 
                       "Veterans' Administration or Board of Veterans' Appeals", 
                       "War Production Board", 
                       "Wage Stabilization Board", 
                       "State Agency", 
                       "Unidentifiable", 
                       "Office of Thrift Supervision", 
                       "Department of Homeland Security", 
                       "Board of General Appraisers", 
                       "Board of Tax Appeals", 
                       "General Land Office or Commissioners", 
                       "No Admin Action", 
                       "Processing Tax Board of Review"]
                       
jurisdiction_labels = ["cert", "appeal", "bail", "certification", "docketing fee", 
                       "rehearing or restored to calendar for reargument", "injunction",
                       "mandamus", "original", "prohibition", "stay", "writ of error",
                       "writ of habeas corpus", "unspecified, other"]
                       
state_labels = ['Alabama',
                'Alaska',
                'American Samoa',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'District of Columbia',
                'Federated States of Micronesia',
                'Florida',
                'Georgia',
                'Guam',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Marshall Islands',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Northern Mariana Islands',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Palau',
                'Pennsylvania',
                'Puerto Rico',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virgin Islands',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
                'United States',
                'Interstate Compact',
                'Philippines',
                'Indian',
                'Dakota']

court_labels = {'1':	'U.S. Court of Customs and Patent Appeals',
'2':	'U.S. Court of International Trade',
'3':	'U.S. Court of Claims, Court of Federal Claims',
'4':	'U.S. Court of Military Appeals, renamed as Court of Appeals for the Armed Forces',
'5':	'U.S. Court of Military Review',
'6':	'U.S. Court of Veterans Appeals',
'7':	'U.S. Customs Court',
'8':	'U.S. Court of Appeals, Federal Circuit',
'9':	'U.S. Tax Court',
'10':	'Temporary Emergency U.S. Court of Appeals',
'12':	'U.S. Court for China',
'13':	'U.S. Consular Courts',
'14':	'U.S. Commerce Court',
'15':	'Territorial Supreme Court',
'16':	'Territorial Appellate Court',
'17':	'Territorial Trial Court',
'18':	'Emergency Court of Appeals',
'19':	'Supreme Court of the District of Columbia',
'20':	'Bankruptcy Court',
'21':	'U.S. Court of Appeals, First Circuit',
'22':	'U.S. Court of Appeals, Second Circuit',
'23':	'U.S. Court of Appeals, Third Circuit',
'24':	'U.S. Court of Appeals, Fourth Circuit',
'25':	'U.S. Court of Appeals, Fifth Circuit',
'26':	'U.S. Court of Appeals, Sixth Circuit',
'27':	'U.S. Court of Appeals, Seventh Circuit',
'28':	'U.S. Court of Appeals, Eighth Circuit',
'29':	'U.S. Court of Appeals, Ninth Circuit',
'30':	'U.S. Court of Appeals, Tenth Circuit',
'31':	'U.S. Court of Appeals, Eleventh Circuit',
'32':	'U.S. Court of Appeals, District of Columbia Circuit',
'41':	'Alabama Middle U.S. District Court',
'42':	'Alabama Northern U.S. District Court',
'43':	'Alabama Southern U.S. District Court',
'44':	'Alaska U.S. District Court',
'45':	'Arizona U.S. District Court',
'46':	'Arkansas Eastern U.S. District Court',
'47':	'Arkansas Western U.S. District Court',
'48':	'California Central U.S. District Court',
'49':	'California Eastern U.S. District Court',
'50':	'California Northern U.S. District Court',
'51':	'California Southern U.S. District Court',
'52':	'Colorado U.S. District Court',
'53':	'Connecticut U.S. District Court',
'54':	'Delaware U.S. District Court',
'55':	'District Of Columbia U.S. District Court',
'56':	'Florida Middle U.S. District Court',
'57':	'Florida Northern U.S. District Court',
'58':	'Florida Southern U.S. District Court',
'59':	'Georgia Middle U.S. District Court',
'60':	'Georgia Northern U.S. District Court',
'61':	'Georgia Southern U.S. District Court',
'62':	'Guam U.S. District Court',
'63':	'Hawaii U.S. District Court',
'64':	'Idaho U.S. District Court',
'65':	'Illinois Central U.S. District Court',
'66':	'Illinois Northern U.S. District Court',
'67':	'Illinois Southern U.S. District Court',
'68':	'Indiana Northern U.S. District Court',
'69':	'Indiana Southern U.S. District Court',
'70':	'Iowa Northern U.S. District Court',
'71':	'Iowa Southern U.S. District Court',
'72':	'Kansas U.S. District Court',
'73':	'Kentucky Eastern U.S. District Court',
'74':	'Kentucky Western U.S. District Court',
'75':	'Louisiana Eastern U.S. District Court',
'76':	'Louisiana Middle U.S. District Court',
'77':	'Louisiana Western U.S. District Court',
'78':	'Maine U.S. District Court',
'79':	'Maryland U.S. District Court',
'80':	'Massachusetts U.S. District Court',
'81':	'Michigan Eastern U.S. District Court',
'82':	'Michigan Western U.S. District Court',
'83':	'Minnesota U.S. District Court',
'84':	'Mississippi Northern U.S. District Court',
'85':	'Mississippi Southern U.S. District Court',
'86':	'Missouri Eastern U.S. District Court',
'87':	'Missouri Western U.S. District Court',
'88':	'Montana U.S. District Court',
'89':	'Nebraska U.S. District Court',
'90':	'Nevada U.S. District Court',
'91':	'New Hampshire U.S. District Court',
'92':	'New Jersey U.S. District Court',
'93':	'New Mexico U.S. District Court',
'94':	'New York Eastern U.S. District Court',
'95':	'New York Northern U.S. District Court',
'96':	'New York Southern U.S. District Court',
'97':	'New York Western U.S. District Court',
'98':	'North Carolina Eastern U.S. District Court',
'99':	'North Carolina Middle U.S. District Court',
'100':	'North Carolina Western U.S. District Court',
'101':	'North Dakota U.S. District Court',
'102':	'Northern Mariana Islands U.S. District Court',
'103':	'Ohio Northern U.S. District Court',
'104':	'Ohio Southern U.S. District Court',
'105':	'Oklahoma Eastern U.S. District Court',
'106':	'Oklahoma Northern U.S. District Court',
'107':	'Oklahoma Western U.S. District Court',
'108':	'Oregon U.S. District Court',
'109':	'Pennsylvania Eastern U.S. District Court',
'110':	'Pennsylvania Middle U.S. District Court',
'111':	'Pennsylvania Western U.S. District Court',
'112':	'Puerto Rico U.S. District Court',
'113':	'Rhode Island U.S. District Court',
'114':	'South Carolina U.S. District Court',
'115':	'South Dakota U.S. District Court',
'116':	'Tennessee Eastern U.S. District Court',
'117':	'Tennessee Middle U.S. District Court',
'118':	'Tennessee Western U.S. District Court',
'119':	'Texas Eastern U.S. District Court',
'120':	'Texas Northern U.S. District Court',
'121':	'Texas Southern U.S. District Court',
'122':	'Texas Western U.S. District Court',
'123':	'Utah U.S. District Court',
'124':	'Vermont U.S. District Court',
'125':	'Virgin Islands U.S. District Court',
'126':	'Virginia Eastern U.S. District Court',
'127':	'Virginia Western U.S. District Court',
'128':	'Washington Eastern U.S. District Court',
'129':	'Washington Western U.S. District Court',
'130':	'West Virginia Northern U.S. District Court',
'131':	'West Virginia Southern U.S. District Court',
'132':	'Wisconsin Eastern U.S. District Court',
'133':	'Wisconsin Western U.S. District Court',
'134':	'Wyoming U.S. District Court',
'150':	'Louisiana U.S. District Court',
'151':	'Washington U.S. District Court',
'152':	'West Virginia U.S. District Court',
'153':	'Illinois Eastern U.S. District Court',
'155':	'South Carolina Eastern U.S. District Court',
'160':	'South Carolina Western U.S. District Court',
'162':	'Alabama U.S. District Court',
'163':	'U.S. District Court for the Canal Zone',
'164':	'Georgia U.S. District Court',
'165':	'Illinois U.S. District Court',
'166':	'Indiana U.S. District Court',
'167':	'Iowa U.S. District Court',
'168':	'Michigan U.S. District Court',
'169':	'Mississippi U.S. District Court',
'170':	'Missouri U.S. District Court',
'171':	'New Jersey Eastern U.S. District Court (East Jersey U.S. District Court)',
'172':	'New Jersey Western U.S. District Court (West Jersey U.S. District Court)',
'173':	'New York U.S. District Court',
'174':	'North Carolina U.S. District Court',
'175':	'Ohio U.S. District Court',
'176':	'Pennsylvania U.S. District Court',
'177':	'Tennessee U.S. District Court',
'178':	'Texas U.S. District Court',
'179':	'Virginia U.S. District Court',
'180':	'Norfolk U.S. District Court',
'181':	'Wisconsin U.S. District Court',
'182':	'Kentucky U.S. Distrcrict Court',
'183':	'New Jersey U.S. District Court',
'184':	'California U.S. District Court',
'185':	'Florida U.S. District Court',
'186':	'Arkansas U.S. District Court',
'187':	'District of Orleans U.S. District Court',
'300':	'State Supreme Court',
'301':	'State Appellate Court',
'302':	'State Trial Court',
'400':	'Eastern Circuit (of the United States)',
'401':	'Middle Circuit (of the United States)',
'402':	'Southern Circuit (of the United States)',
'403':	'Alabama U.S. Circuit Court for (all) District(s) of Alabama',
'404':	'Arkansas U.S. Circuit Court for (all) District(s) of Arkansas',
'405':	'California U.S. Circuit for (all) District(s) of California',
'406':	'Connecticut U.S. Circuit for the District of Connecticut',
'407':	'Delaware U.S. Circuit for the District of Delaware',
'408':	'Florida U.S. Circuit for (all) District(s) of Florida',
'409':	'Georgia U.S. Circuit for (all) District(s) of Georgia',
'410':	'Illinois U.S. Circuit for (all) District(s) of Illinois',
'411':	'Indiana U.S. Circuit for (all) District(s) of Indiana',
'412':	'Iowa U.S. Circuit for (all) District(s) of Iowa',
'413':	'Kansas U.S. Circuit for the District of Kansas',
'414':	'Kentucky U.S. Circuit for (all) District(s) of Kentucky',
'415':	'Louisiana U.S. Circuit for (all) District(s) of Louisiana',
'416':	'Maine U.S. Circuit for the District of Maine',
'417':	'Maryland U.S. Circuit for the District of Maryland',
'418':	'Massachusetts U.S. Circuit for the District of Massachusetts',
'419':	'Michigan U.S. Circuit for (all) District(s) of Michigan',
'420':	'Minnesota U.S. Circuit for the District of Minnesota',
'421':	'Mississippi U.S. Circuit for (all) District(s) of Mississippi',
'422':	'Missouri U.S. Circuit for (all) District(s) of Missouri',
'423':	'Nevada U.S. Circuit for the District of Nevada',
'424':	'New Hampshire U.S. Circuit for the District of New Hampshire',
'425':	'New Jersey U.S. Circuit for (all) District(s) of New Jersey',
'426':	'New York U.S. Circuit for (all) District(s) of New York',
'427':	'North Carolina U.S. Circuit for (all) District(s) of North Carolina',
'428':	'Ohio U.S. Circuit for (all) District(s) of Ohio',
'429':	'Oregon U.S. Circuit for the District of Oregon',
'430':	'Pennsylvania U.S. Circuit for (all) District(s) of Pennsylvania',
'431':	'Rhode Island U.S. Circuit for the District of Rhode Island',
'432':	'South Carolina U.S. Circuit for the District of South Carolina',
'433':	'Tennessee U.S. Circuit for (all) District(s) of Tennessee',
'434':	'Texas U.S. Circuit for (all) District(s) of Texas',
'435':	'Vermont U.S. Circuit for the District of Vermont',
'436':	'Virginia U.S. Circuit for (all) District(s) of Virginia',
'437':	'West Virginia U.S. Circuit for (all) District(s) of West Virginia',
'438':	'Wisconsin U.S. Circuit for (all) District(s) of Wisconsin',
'439':	'Wyoming U.S. Circuit for the District of Wyoming',
'440':	'Circuit Court of the District of Columbia',
'441':	'Nebraska U.S. Circuit for the District of Nebraska',
'442':	'Colorado U.S. Circuit for the District of Colorado',
'443':	'Washington U.S. Circuit for (all) District(s) of Washington',
'444':	'Idaho U.S. Circuit Court for (all) District(s) of Idaho',
'445':	'Montana U.S. Circuit Court for (all) District(s) of Montana',
'446':	'Utah U.S. Circuit Court for (all) District(s) of Utah',
'447':	'South Dakota U.S. Circuit Court for (all) District(s) of South Dakota',
'448':	'North Dakota U.S. Circuit Court for (all) District(s) of North Dakota',
'449':	'Oklahoma U.S. Circuit Court for (all) District(s) of Oklahoma',
'601':	'Court of Private Land Claims'} 
                
cert_labels = ["case did not arise on cert or cert not granted",
               "federal court conflict",
               "federal court conflict and to resolve important or significant question",
               "putative conflict",
               "conflict between federal court and state court",
               "state court conflict",
               "federal court confusion or uncertainty",
               "state court confusion or uncertainty",
               "federal court and state court confusion or uncertainty",
               "to resolve important or significant question",
               "to resolve question presented",
               "no reason given",
               "other reason"]
               
lc_disposition_labels = ['stay, petition, or motion granted',
                      'affirmed',
                      'reversed',
                      'reversed and remanded',
                      'vacated and remanded',
                      'affirmed and reversed (or vacated) in part',
                      'affirmed and reversed (or vacated) in part and remanded',
                      'vacated',
                      'petition denied or appeal dismissed',
                      'modify',
                      'remand',
                      'unusual disposition']

sc_disposition_labels = [
'stay, petition, or motion granted',
'affirmed (includes modified)',
'reversed',
'reversed and remanded',
'vacated and remanded',
'affirmed and reversed (or vacated) in part',
'affirmed and reversed (or vacated) in part and remanded',
'vacated',
'petition denied or appeal dismissed',
'certification to or from a lower court',
'no disposition']
                      
direction_labels = ['conservative', 'liberal', 'unspecifiable']

decision_kind = ['majority opinion', #"opinion of the court (orally argued)",
                 'per curiam', #"per curiam (no oral argument)",
                 "decrees",
                 "equally divided vote",
                 'per curiam', #"per curiam (orally argued)",
                 'plurality opinion', #"judgment of the Court (orally argued)",
                 "seriatim"]
                 
party_codes = {'1':	'attorney general of the United States, or his office',
'2':	'specified state board or department of education',
'3':	'city, town, township, village, or borough government or governmental unit',
'4':	'state commission, board, committee, or authority',
'5':	'county government or county governmental unit, except school district',
'6':	'court or judicial district',
'7':	'state department or agency',
'8':	'governmental employee or job applicant',
'9':	'female governmental employee or job applicant',
'10':	'minority governmental employee or job applicant',
'11':	'minority female governmental employee or job applicant',
'12':	'not listed among agencies in the first Administrative Action variable',
'13':	'retired or former governmental employee',
'14':	'U.S. House of Representatives',
'15':	'interstate compact',
'16':	'judge',
'17':	'state legislature, house, or committee',
'18':	'local governmental unit other than a county, city, town, township, village, or borough',
'19':	'governmental official, or an official of an agency established under an interstate compact',
'20':	'state or U.S. supreme court',
'21':	'local school district or board of education',
'22':	'U.S. Senate',
'23':	'U.S. senator',
'24':	'foreign nation or instrumentality',
'25':	'state or local governmental taxpayer, or executor of the estate of',
'26':	'state college or university',
'27':	'United States',
'28':	'State',
'100':	'person accused, indicted, or suspected of crime',
'101':	'advertising business or agency',
'102':	'agent, fiduciary, trustee, or executor',
'103':	'airplane manufacturer, or manufacturer of parts of airplanes',
'104':	'airline',
'105':	'distributor, importer, or exporter of alcoholic beverages',
'106':	'alien, person subject to a denaturalization proceeding, or one whose citizenship is revoked',
'107':	'American Medical Association',
'108':	'National Railroad Passenger Corp.',
'109':	'amusement establishment, or recreational facility',
'110':	'arrested person, or pretrial detainee',
'111':	'attorney, or person acting as such;includes bar applicant or law student, or law firm or bar association',
'112':	'author, copyright holder',
'113':	'bank, savings and loan, credit union, investment company',
'114':	'bankrupt person or business, or business in reorganization',
'115':	'establishment serving liquor by the glass, or package liquor store',
'116':	'water transportation, stevedore',
'117':	'bookstore, newsstand, printer, bindery, purveyor or distributor of books or magazines',
'118':	'brewery, distillery',
'119':	'broker, stock exchange, investment or securities firm',
'120':	'construction industry',
'121':	'bus or motorized passenger transportation vehicle',
'122':	'business, corporation',
'123':	'buyer, purchaser',
'124':	'cable TV',
'125':	'car dealer',
'126':	'person convicted of crime',
'127':	'tangible property, other than real estate, including contraband',
'128':	'chemical company',
'129':	'child, children, including adopted or illegitimate',
'130':	'religious organization, institution, or person',
'131':	'private club or facility',
'132':	'coal company or coal mine operator',
'133':	'computer business or manufacturer, hardware or software',
'134':	'consumer, consumer organization',
'135':	'creditor, including institution appearing as such; e.g., a finance company',
'136':	'person allegedly criminally insane or mentally incompetent to stand trial',
'137':	'defendant',
'138':	'debtor',
'139':	'real estate developer',
'140':	'disabled person or disability benefit claimant',
'141':	'distributor',
'142':	'person subject to selective service, including conscientious objector',
'143':	'drug manufacturer',
'144':	'druggist, pharmacist, pharmacy',
'145':	'employee, or job applicant, including beneficiaries of',
'146':	'employer-employee trust agreement, employee health and welfare fund, or multi-employer pension plan',
'147':	'electric equipment manufacturer',
'148':	'electric or hydroelectric power utility, power cooperative, or gas and electric company',
'149':	'eleemosynary institution or person',
'150':	'environmental organization',
'151':	'employer. If employer\'s relations with employees are governed by the nature of the employer\'s business (e.g., railroad, boat), rather than labor law generally, the more specific designation is used in place of Employer.',
'152':	'farmer, farm worker, or farm organization',
'153':	'father',
'154':	'female employee or job applicant',
'155':	'female',
'156':	'movie, play, pictorial representation, theatrical production, actor, or exhibitor or distributor of',
'157':	'fisherman or fishing company',
'158':	'food, meat packing, or processing company, stockyard',
'159':	'foreign (non-American) nongovernmental entity',
'160':	'franchiser',
'161':	'franchisee',
'162':	'lesbian, gay, bisexual, transexual person or organization',
'163':	'person who guarantees another\'s obligations',
'164':	'handicapped individual, or organization of devoted to',
'165':	'health organization or person, nursing home, medical clinic or laboratory, chiropractor',
'166':	'heir, or beneficiary, or person so claiming to be',
'167':	'hospital, medical center',
'168':	'husband, or ex-husband',
'169':	'involuntarily committed mental patient',
'170':	'Indian, including Indian tribe or nation',
'171':	'insurance company, or surety',
'172':	'inventor, patent assigner, trademark owner or holder',
'173':	'investor',
'174':	'injured person or legal entity, nonphysically and non-employment related',
'175':	'juvenile',
'176':	'government contractor',
'177':	'holder of a license or permit, or applicant therefor',
'178':	'magazine',
'179':	'male',
'180':	'medical or Medicaid claimant',
'181':	'medical supply or manufacturing co.',
'182':	'racial or ethnic minority employee or job applicant',
'183':	'minority female employee or job applicant',
'184':	'manufacturer',
'185':	'management, executive officer, or director, of business entity',
'186':	'military personnel, or dependent of, including reservist',
'187':	'mining company or miner, excluding coal, oil, or pipeline company',
'188':	'mother',
'189':	'auto manufacturer',
'190':	'newspaper, newsletter, journal of opinion, news service',
'191':	'radio and television network, except cable tv',
'192':	'nonprofit organization or business',
'193':	'nonresident',
'194':	'nuclear power plant or facility',
'195':	'owner, landlord, or claimant to ownership, fee interest, or possession of land as well as chattels',
'196':	'shareholders to whom a tender offer is made',
'197':	'tender offer',
'198':	'oil company, or natural gas producer',
'199':	'elderly person, or organization dedicated to the elderly',
'200':	'out of state noncriminal defendant',
'201':	'political action committee',
'202':	'parent or parents',
'203':	'parking lot or service',
'204':	'patient of a health professional',
'205':	'telephone, telecommunications, or telegraph company',
'206':	'physician, MD or DO, dentist, or medical society',
'207':	'public interest organization',
'208':	'physically injured person, including wrongful death, who is not an employee',
'209':	'pipe line company',
'210':	'package, luggage, container',
'211':	'political candidate, activist, committee, party, party member, organization, or elected official',
'212':	'indigent, needy, welfare recipient',
'213':	'indigent defendant',
'214':	'private person',
'215':	'prisoner, inmate of penal institution',
'216':	'professional organization, business, or person',
'217':	'probationer, or parolee',
'218':	'protester, demonstrator, picketer or pamphleteer (non-employment related), or non-indigent loiterer',
'219':	'public utility',
'220':	'publisher, publishing company',
'221':	'radio station',
'222':	'racial or ethnic minority',
'223':	'person or organization protesting racial or ethnic segregation or discrimination',
'224':	'racial or ethnic minority student or applicant for admission to an educational institution',
'225':	'realtor',
'226':	'journalist, columnist, member of the news media',
'227':	'resident',
'228':	'restaurant, food vendor',
'229':	'retarded person, or mental incompetent',
'230':	'retired or former employee',
'231':	'railroad',
'232':	'private school, college, or university',
'233':	'seller or vendor',
'234':	'shipper, including importer and exporter',
'235':	'shopping center, mall',
'236':	'spouse, or former spouse',
'237':	'stockholder, shareholder, or bondholder',
'238':	'retail business or outlet',
'239':	'student, or applicant for admission to an educational institution',
'240':	'taxpayer or executor of taxpayer\'s estate, federal only',
'241':	'tenant or lessee',
'242':	'theater, studio',
'243':	'forest products, lumber, or logging company',
'244':	'person traveling or wishing to travel abroad, or overseas travel agent',
'245':	'trucking company, or motor carrier',
'246':	'television station',
'247':	'union member',
'248':	'unemployed person or unemployment compensation applicant or claimant',
'249':	'union, labor organization, or official of',
'250':	'veteran',
'251':	'voter, prospective voter, elector, or a nonelective official seeking reapportionment or redistricting of legislative districts (POL)',
'252':	'wholesale trade',
'253':	'wife, or ex-wife',
'254':	'witness, or person under subpoena',
'255':	'network',
'256':	'slave',
'257':	'slave-owner',
'258':	'bank of the united states',
'259':	'timber company',
'260':	'u.s. job applicants or employees',
'301':	'Army and Air Force Exchange Service',
'302':	'Atomic Energy Commission',
'303':	'Secretary or administrative unit or personnel of the U.S. Air Force',
'304':	'Department or Secretary of Agriculture',
'305':	'Alien Property Custodian',
'306':	'Secretary or administrative unit or personnel of the U.S. Army',
'307':	'Board of Immigration Appeals',
'308':	'Bureau of Indian Affairs',
'310':	'Bonneville Power Administration',
'311':	'Benefits Review Board',
'312':	'Civil Aeronautics Board',
'313':	'Bureau of the Census',
'314':	'Central Intelligence Agency',
'315':	'Commodity Futures Trading Commission',
'316':	'Department or Secretary of Commerce',
'317':	'Comptroller of Currency',
'318':	'Consumer Product Safety Commission',
'319':	'Civil Rights Commission',
'320':	'Civil Service Commission, U.S.',
'321':	'Customs Service or Commissioner of Customs',
'322':	'Defense Base Closure and REalignment Commission',
'323':	'Drug Enforcement Agency',
'324':	'Department or Secretary of Defense (and Department or Secretary of War)',
'325':	'Department or Secretary of Energy',
'326':	'Department or Secretary of the Interior',
'327':	'Department of Justice or Attorney General',
'328':	'Department or Secretary of State',
'329':	'Department or Secretary of Transportation',
'330':	'Department or Secretary of Education',
'331':	'U.S. Employees\' Compensation Commission, or Commissioner',
'332':	'Equal Employment Opportunity Commission',
'333':	'Environmental Protection Agency or Administrator',
'334':	'Federal Aviation Agency or Administration',
'335':	'Federal Bureau of Investigation or Director',
'336':	'Federal Bureau of Prisons',
'337':	'Farm Credit Administration',
'338':	'Federal Communications Commission (including a predecessor, Federal Radio Commission)',
'339':	'Federal Credit Union Administration',
'340':	'Food and Drug Administration',
'341':	'Federal Deposit Insurance Corporation',
'342':	'Federal Energy Administration',
'343':	'Federal Election Commission',
'344':	'Federal Energy Regulatory Commission',
'345':	'Federal Housing Administration',
'346':	'Federal Home Loan Bank Board',
'347':	'Federal Labor Relations Authority',
'348':	'Federal Maritime Board',
'349':	'Federal Maritime Commission',
'350':	'Farmers Home Administration',
'351':	'Federal Parole Board',
'352':	'Federal Power Commission',
'353':	'Federal Railroad Administration',
'354':	'Federal Reserve Board of Governors',
'355':	'Federal Reserve System',
'356':	'Federal Savings and Loan Insurance Corporation',
'357':	'Federal Trade Commission',
'358':	'Federal Works Administration, or Administrator',
'359':	'General Accounting Office',
'360':	'Comptroller General',
'361':	'General Services Administration',
'362':	'Department or Secretary of Health, Education and Welfare',
'363':	'Department or Secretary of Health and Human Services',
'364':	'Department or Secretary of Housing and Urban Development',
'366':	'Interstate Commerce Commission',
'367':	'Indian Claims Commission',
'368':	'Immigration and Naturalization Service, or Director of, or District Director of, or Immigration and Naturalization Enforcement',
'369':	'Internal Revenue Service, Collector, Commissioner, or District Director of',
'370':	'Information Security Oversight Office',
'371':	'Department or Secretary of Labor',
'372':	'Loyalty Review Board',
'373':	'Legal Services Corporation',
'374':	'Merit Systems Protection Board',
'375':	'Multistate Tax Commission',
'376':	'National Aeronautics and Space Administration',
'377':	'Secretary or administrative unit of the U.S. Navy',
'378':	'National Credit Union Administration',
'379':	'National Endowment for the Arts',
'380':	'National Enforcement Commission',
'381':	'National Highway Traffic Safety Administration',
'382':	'National Labor Relations Board, or regional office or officer',
'383':	'National Mediation Board',
'384':	'National Railroad Adjustment Board',
'385':	'Nuclear Regulatory Commission',
'386':	'National Security Agency',
'387':	'Office of Economic Opportunity',
'388':	'Office of Management and Budget',
'389':	'Office of Price Administration, or Price Administrator',
'390':	'Office of Personnel Management',
'391':	'Occupational Safety and Health Administration',
'392':	'Occupational Safety and Health Review Commission',
'393':	'Office of Workers\' Compensation Programs',
'394':	'Patent Office, or Commissioner of, or Board of Appeals of',
'395':	'Pay Board (established under the Economic Stabilization Act of 1970)',
'396':	'Pension Benefit Guaranty Corporation',
'397':	'U.S. Public Health Service',
'398':	'Postal Rate Commission',
'399':	'Provider Reimbursement Review Board',
'400':	'Renegotiation Board',
'401':	'Railroad Adjustment Board',
'402':	'Railroad Retirement Board',
'403':	'Subversive Activities Control Board',
'404':	'Small Business Administration',
'405':	'Securities and Exchange Commission',
'406':	'Social Security Administration or Commissioner',
'407':	'Selective Service System',
'408':	'Department or Secretary of the Treasury',
'409':	'Tennessee Valley Authority',
'410':	'United States Forest Service',
'411':	'United States Parole Commission',
'412':	'Postal Service and Post Office, or Postmaster General, or Postmaster',
'413':	'United States Sentencing Commission',
'414':	'Veterans\' Administration',
'415':	'War Production Board',
'416':	'Wage Stabilization Board',
'417':	'General Land Office of Commissioners',
'418':	'Transportation Security Administration',
'419':	'Surface Transportation Board',
'420':	'U.S. Shipping Board Emergency Fleet Corp.',
'421':	'Reconstruction Finance Corp.',
'501':	'Unidentifiable',
'600':	'International Entity'}

justice_names = [
'John Jay',
'John Rutledge',
'William Cushing',
'James Wilson',
'John Blair, Jr.',
'James Iredell',
'Thomas Johnson',
'William Paterson',
'John Rutledge',
'Samuel Chase',
'Oliver Ellsworth',
'Bushrod Washington',
'Alfred Moore',
'John Marshall',
'William Johnson',
'Henry Brockholst Livingston',
'Thomas Todd',
'Gabriel Duvall',
'Joseph Story',
'Smith Thompson',
'Robert Trimble',
'Henry Baldwin',
'John McLean',
'James M. Wayne',
'Roger B. Taney',
'Philip P. Barbour',
'John Catron',
'John McKinley',
'Peter V. Daniel',
'Samuel Nelson',
'Levi Woodbury',
'Robert C. Grier',
'Benjamin R. Curtis',
'John A. Campbell',
'Nathan Clifford',
'Noah Swayne',
'Samuel F. Miller',
'David Davis',
'Stephen J. Field',
'Salmon P. Chase',
'William Strong',
'Joseph P. Bradley',
'Ward Hunt',
'Morrison R. Waite',
'John M. Harlan',
'William B. Woods',
'Stanley Matthews',
'Horace Gray',
'Samuel Blatchford',
'Lucius Q.C. Lamar',
'Melville W. Fuller',
'David J. Brewer',
'Henry B. Brown',
'George Shiras, Jr.',
'Howell E. Jackson',
'Edward D. White',
'Rufus Peckham',
'Joseph McKenna',
'Oliver W. Holmes, Jr.',
'William R. Day',
'William H. Moody',
'Horace H. Lurton',
'Charles E. Hughes',
'Willis Van Devanter',
'Joseph R. Lamar',
'Mahlon Pitney',
'James C. McReynolds',
'Louis D. Brandeis',
'John H. Clarke',
'William Howard Taft',
'George Sutherland',
'Pierce Butler',
'Edward T. Sanford',
'Harlan Fiske Stone',
'Charles E. Hughes',
'Owen J. Roberts',
'Benjamin N. Cardozo',
'Hugo L. Black',
'Stanley Reed',
'Felix Frankfurter',
'William O. Douglas',
'Frank Murphy',
'James F. Byrnes',
'Robert H. Jackson',
'Wiley B. Rutledge',
'Harold Burton',
'Fred M. Vinson',
'Tom C. Clark',
'Sherman Minton',
'Earl Warren',
'John M. Harlan II',
'William J. Brennan, Jr.',
'Charles E. Whittaker',
'Potter Stewart',
'Byron R. White',
'Arthur J. Goldberg',
'Abe Fortas',
'Thurgood Marshall',
'Warren E. Burger',
'Harry A. Blackmun',
'Lewis F. Powell, Jr.',
'William H. Rehnquist',
'John Paul Stevens',
'Sandra Day O\'Connor',
'Antonin Scalia',
'Anthony M. Kennedy',
'David H. Souter',
'Clarence Thomas',
'Ruth Bader Ginsburg',
'Stephen G. Breyer',
'John G. Roberts, Jr.',
'Samuel A. Alito, Jr.',
'Sonia Sotomayor',
'Elena Kagan',
]

female_justices = ['Sonia Sotomayor', 'Elena Kagan', 'Sandra Day O\'Connor','Ruth Bader Ginsburg']             

vote_labels=['voted with majority or plurality',
'dissent',
'regular concurrence',
'special concurrence',
'judgment of the Court',
'dissent from a denial or dismissal of certiorari , or dissent from summary affirmation of an appeal',
'jurisdictional dissent',
'justice participated in an equally divided vote    ']