admin_agency_labels = ["Army and Air Force Exchange Service", 
                       "Atomic Energy Commission", 
                       "Secretary or administrative unit or personnel of the U.S. Air Force", 
                       "Department or Secretary of Agriculture", 
                       "Alien Property Custodian", 
                       "Secretary or administrative unit or personnel of the U.S. Army", 
                       "Board of Immigration Appeals", 
                       "Bureau of Indian Affairs", 
                       "Bureau of Prisons", 
                       "Bonneville Power Administration", 
                       "Benefits Review Board", 
                       "Civil Aeronautics Board", 
                       "Bureau of the Census", 
                       "Central Intelligence Agency", 
                       "Commodity Futures Trading Commission", 
                       "Department or Secretary of Commerce", 
                       "Comptroller of Currency", 
                       "Consumer Product Safety Commission", 
                       "Civil Rights Commission", 
                       "Civil Service Commission, U.S.", 
                       "Customs Service or Commissioner or Collector of Customs", 
                       "Defense Base Closure and REalignment Commission", 
                       "Drug Enforcement Agency", 
                       "Department or Secretary of Defense (and Department or Secretary of War)", 
                       "Department or Secretary of Energy", 
                       "Department or Secretary of the Interior", 
                       "Department of Justice or Attorney General", 
                       "Department or Secretary of State", 
                       "Department or Secretary of Transportation", 
                       "Department or Secretary of Education", 
                       "U.S. Employees' Compensation Commission, or Commissioner", 
                       "Equal Employment Opportunity Commission", 
                       "Environmental Protection Agency or Administrator", 
                       "Federal Aviation Agency or Administration", 
                       "Federal Bureau of Investigation or Director", 
                       "Federal Bureau of Prisons", 
                       "Farm Credit Administration", 
                       "Federal Communications Commission (including a predecessor, Federal Radio Commission)", 
                       "Federal Credit Union Administration", 
                       "Food and Drug Administration", 
                       "Federal Deposit Insurance Corporation", 
                       "Federal Energy Administration", 
                       "Federal Election Commission", 
                       "Federal Energy Regulatory Commission", 
                       "Federal Housing Administration", 
                       "Federal Home Loan Bank Board", 
                       "Federal Labor Relations Authority", 
                       "Federal Maritime Board", 
                       "Federal Maritime Commission", 
                       "Farmers Home Administration", 
                       "Federal Parole Board", 
                       "Federal Power Commission", 
                       "Federal Railroad Administration", 
                       "Federal Reserve Board of Governors", 
                       "Federal Reserve System", 
                       "Federal Savings and Loan Insurance Corporation", 
                       "Federal Trade Commission", 
                       "Federal Works Administration, or Administrator", 
                       "General Accounting Office", 
                       "Comptroller General", 
                       "General Services Administration", 
                       "Department or Secretary of Health, Education and Welfare", 
                       "Department or Secretary of Health and Human Services", 
                       "Department or Secretary of Housing and Urban Development", 
                       "Administrative agency established under an interstate compact (except for the MTC)", 
                       "Interstate Commerce Commission", 
                       "Indian Claims Commission", 
                       "Immigration and Naturalization Service, or Director of, or District Director of, or Immigration and Naturalization Enforcement", 
                       "Internal Revenue Service, Collector, Commissioner, or District Director of", 
                       "Information Security Oversight Office", 
                       "Department or Secretary of Labor", 
                       "Loyalty Review Board", 
                       "Legal Services Corporation", 
                       "Merit Systems Protection Board", 
                       "Multistate Tax Commission", 
                       "National Aeronautics and Space Administration", 
                       "Secretary or administrative unit or personnel of the U.S. Navy", 
                       "National Credit Union Administration", 
                       "National Endowment for the Arts", 
                       "National Enforcement Commission", 
                       "National Highway Traffic Safety Administration", 
                       "National Labor Relations Board, or regional office or officer", 
                       "National Mediation Board", 
                       "National Railroad Adjustment Board", 
                       "Nuclear Regulatory Commission", 
                       "National Security Agency", 
                       "Office of Economic Opportunity", 
                       "Office of Management and Budget", 
                       "Office of Price Administration, or Price Administrator", 
                       "Office of Personnel Management", 
                       "Occupational Safety and Health Administration", 
                       "Occupational Safety and Health Review Commission", 
                       "Office of Workers' Compensation Programs", 
                       "Patent Office, or Commissioner of, or Board of Appeals of", 
                       "Pay Board (established under the Economic Stabilization Act of 1970)", 
                       "Pension Benefit Guaranty Corporation", 
                       "U.S. Public Health Service", 
                       "Postal Rate Commission", 
                       "Provider Reimbursement Review Board", 
                       "Renegotiation Board", 
                       "Railroad Adjustment Board", 
                       "Railroad Retirement Board", 
                       "Subversive Activities Control Board", 
                       "Small Business Administration", 
                       "Securities and Exchange Commission", 
                       "Social Security Administration or Commissioner", 
                       "Selective Service System", 
                       "Department or Secretary of the Treasury", 
                       "Tennessee Valley Authority", 
                       "United States Forest Service", 
                       "United States Parole Commission", 
                       "Postal Service and Post Office, or Postmaster General, or Postmaster", 
                       "United States Sentencing Commission", 
                       "Veterans' Administration or Board of Veterans' Appeals", 
                       "War Production Board", 
                       "Wage Stabilization Board", 
                       "State Agency", 
                       "Unidentifiable", 
                       "Office of Thrift Supervision", 
                       "Department of Homeland Security", 
                       "Board of General Appraisers", 
                       "Board of Tax Appeals", 
                       "General Land Office or Commissioners", 
                       "No Admin Action", 
                       "Processing Tax Board of Review"]
                       
juristiction_labels = ["cert", "appeal", "bail", "certification", "docketing fee", 
                       "rehearing or restored to calendar for reargument", "injunction",
                       "mandamus", "original", "prohibition", "stay", "writ of error",
                       "writ of habeas corpus", "unspecified, other"]
                       
state_labels = ['Alabama',
                'Alaska',
                'American Samoa',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'District of Columbia',
                'Federated States of Micronesia',
                'Florida',
                'Georgia',
                'Guam',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Marshall Islands',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Northern Mariana Islands',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Palau',
                'Pennsylvania',
                'Puerto Rico',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virgin Islands',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
                'United States',
                'Interstate Compact',
                'Philippines',
                'Indian',
                'Dakota']

court_labels = ["U.S. Court of Customs and Patent Appeals",
                "U.S. Court of International Trade",
                "U.S. Court of Claims, Court of Federal Claims",
                "U.S. Court of Military Appeals, renamed as Court of Appeals for the Armed Forces",
                "U.S. Court of Military Review",
                "U.S. Court of Veterans Appeals",
                "U.S. Customs Court",
                "U.S. Court of Appeals, Federal Circuit",
                "U.S. Tax Court",
                "Temporary Emergency U.S. Court of Appeals",
                "U.S. Court for China",
                "U.S. Consular Courts",
                "U.S. Commerce Court",
                "Territorial Supreme Court",
                "Territorial Appellate Court",
                "Territorial Trial Court",
                "Emergency Court of Appeals",
                "Supreme Court of the District of Columbia",
                "Bankruptcy Court",
                "U.S. Court of Appeals, First Circuit",
                "U.S. Court of Appeals, Second Circuit",
                "U.S. Court of Appeals, Third Circuit",
                "U.S. Court of Appeals, Fourth Circuit",
                "U.S. Court of Appeals, Fifth Circuit",
                "U.S. Court of Appeals, Sixth Circuit",
                "U.S. Court of Appeals, Seventh Circuit",
                "U.S. Court of Appeals, Eighth Circuit",
                "U.S. Court of Appeals, Ninth Circuit",
                "U.S. Court of Appeals, Tenth Circuit",
                "U.S. Court of Appeals, Eleventh Circuit",
                "U.S. Court of Appeals, District of Columbia Circuit",
                "Alabama Middle U.S. District Court",
                "Alabama Northern U.S. District Court",
                "Alabama Southern U.S. District Court",
                "Alaska U.S. District Court",
                "Arizona U.S. District Court",
                "Arkansas Eastern U.S. District Court",
                "Arkansas Western U.S. District Court",
                "California Central U.S. District Court",
                "California Eastern U.S. District Court",
                "California Northern U.S. District Court",
                "California Southern U.S. District Court",
                "Colorado U.S. District Court",
                "Connecticut U.S. District Court",
                "Delaware U.S. District Court",
                "District Of Columbia U.S. District Court",
                "Florida Middle U.S. District Court",
                "Florida Northern U.S. District Court",
                "Florida Southern U.S. District Court",
                "Georgia Middle U.S. District Court",
                "Georgia Northern U.S. District Court",
                "Georgia Southern U.S. District Court",
                "Guam U.S. District Court",
                "Hawaii U.S. District Court",
                "Idaho U.S. District Court",
                "Illinois Central U.S. District Court",
                "Illinois Northern U.S. District Court",
                "Illinois Southern U.S. District Court",
                "Indiana Northern U.S. District Court",
                "Indiana Southern U.S. District Court",
                "Iowa Northern U.S. District Court",
                "Iowa Southern U.S. District Court",
                "Kansas U.S. District Court",
                "Kentucky Eastern U.S. District Court",
                "Kentucky Western U.S. District Court",
                "Louisiana Eastern U.S. District Court",
                "Louisiana Middle U.S. District Court",
                "Louisiana Western U.S. District Court",
                "Maine U.S. District Court",
                "Maryland U.S. District Court",
                "Massachusetts U.S. District Court",
                "Michigan Eastern U.S. District Court",
                "Michigan Western U.S. District Court",
                "Minnesota U.S. District Court",
                "Mississippi Northern U.S. District Court",
                "Mississippi Southern U.S. District Court",
                "Missouri Eastern U.S. District Court",
                "Missouri Western U.S. District Court",
                "Montana U.S. District Court",
                "Nebraska U.S. District Court",
                "Nevada U.S. District Court",
                "New Hampshire U.S. District Court",
                "New Jersey U.S. District Court",
                "New Mexico U.S. District Court",
                "New York Eastern U.S. District Court",
                "New York Northern U.S. District Court",
                "New York Southern U.S. District Court",
                "New York Western U.S. District Court",
                "North Carolina Eastern U.S. District Court",
                "North Carolina Middle U.S. District Court",
                "North Carolina Western U.S. District Court",
                "North Dakota U.S. District Court",
                "Northern Mariana Islands U.S. District Court",
                "Ohio Northern U.S. District Court",
                "Ohio Southern U.S. District Court",
                "Oklahoma Eastern U.S. District Court",
                "Oklahoma Northern U.S. District Court",
                "Oklahoma Western U.S. District Court",
                "Oregon U.S. District Court",
                "Pennsylvania Eastern U.S. District Court",
                "Pennsylvania Middle U.S. District Court",
                "Pennsylvania Western U.S. District Court",
                "Puerto Rico U.S. District Court",
                "Rhode Island U.S. District Court",
                "South Carolina U.S. District Court",
                "South Dakota U.S. District Court",
                "Tennessee Eastern U.S. District Court",
                "Tennessee Middle U.S. District Court",
                "Tennessee Western U.S. District Court",
                "Texas Eastern U.S. District Court",
                "Texas Northern U.S. District Court",
                "Texas Southern U.S. District Court",
                "Texas Western U.S. District Court",
                "Utah U.S. District Court",
                "Vermont U.S. District Court",
                "Virgin Islands U.S. District Court",
                "Virginia Eastern U.S. District Court",
                "Virginia Western U.S. District Court",
                "Washington Eastern U.S. District Court",
                "Washington Western U.S. District Court",
                "West Virginia Northern U.S. District Court",
                "West Virginia Southern U.S. District Court",
                "Wisconsin Eastern U.S. District Court",
                "Wisconsin Western U.S. District Court",
                "Wyoming U.S. District Court",
                "Louisiana U.S. District Court",
                "Washington U.S. District Court",
                "West Virginia U.S. District Court",
                "Illinois Eastern U.S. District Court",
                "South Carolina Eastern U.S. District Court",
                "South Carolina Western U.S. District Court",
                "Alabama U.S. District Court",
                "U.S. District Court for the Canal Zone",
                "Georgia U.S. District Court",
                "Illinois U.S. District Court",
                "Indiana U.S. District Court",
                "Iowa U.S. District Court",
                "Michigan U.S. District Court",
                "Mississippi U.S. District Court",
                "Missouri U.S. District Court",
                "New Jersey Eastern U.S. District Court (East Jersey U.S. District Court)",
                "New Jersey Western U.S. District Court (West Jersey U.S. District Court)",
                "New York U.S. District Court",
                "North Carolina U.S. District Court",
                "Ohio U.S. District Court",
                "Pennsylvania U.S. District Court",
                "Tennessee U.S. District Court",
                "Texas U.S. District Court",
                "Virginia U.S. District Court",
                "Norfolk U.S. District Court",
                "Wisconsin U.S. District Court",
                "Kentucky U.S. Distrcrict Court",
                "New Jersey U.S. District Court",
                "California U.S. District Court",
                "Florida U.S. District Court",
                "Arkansas U.S. District Court",
                "District of Orleans U.S. District Court",
                "State Supreme Court",
                "State Appellate Court",
                "State Trial Court",
                "Eastern Circuit (of the United States)",
                "Middle Circuit (of the United States)",
                "Southern Circuit (of the United States)",
                "Alabama U.S. Circuit Court for (all) District(s) of Alabama",
                "Arkansas U.S. Circuit Court for (all) District(s) of Arkansas",
                "California U.S. Circuit for (all) District(s) of California",
                "Connecticut U.S. Circuit for the District of Connecticut",
                "Delaware U.S. Circuit for the District of Delaware",
                "Florida U.S. Circuit for (all) District(s) of Florida",
                "Georgia U.S. Circuit for (all) District(s) of Georgia",
                "Illinois U.S. Circuit for (all) District(s) of Illinois",
                "Indiana U.S. Circuit for (all) District(s) of Indiana",
                "Iowa U.S. Circuit for (all) District(s) of Iowa",
                "Kansas U.S. Circuit for the District of Kansas",
                "Kentucky U.S. Circuit for (all) District(s) of Kentucky",
                "Louisiana U.S. Circuit for (all) District(s) of Louisiana",
                "Maine U.S. Circuit for the District of Maine",
                "Maryland U.S. Circuit for the District of Maryland",
                "Massachusetts U.S. Circuit for the District of Massachusetts",
                "Michigan U.S. Circuit for (all) District(s) of Michigan",
                "Minnesota U.S. Circuit for the District of Minnesota",
                "Mississippi U.S. Circuit for (all) District(s) of Mississippi",
                "Missouri U.S. Circuit for (all) District(s) of Missouri",
                "Nevada U.S. Circuit for the District of Nevada",
                "New Hampshire U.S. Circuit for the District of New Hampshire",
                "New Jersey U.S. Circuit for (all) District(s) of New Jersey",
                "New York U.S. Circuit for (all) District(s) of New York",
                "North Carolina U.S. Circuit for (all) District(s) of North Carolina",
                "Ohio U.S. Circuit for (all) District(s) of Ohio",
                "Oregon U.S. Circuit for the District of Oregon",
                "Pennsylvania U.S. Circuit for (all) District(s) of Pennsylvania",
                "Rhode Island U.S. Circuit for the District of Rhode Island",
                "South Carolina U.S. Circuit for the District of South Carolina",
                "Tennessee U.S. Circuit for (all) District(s) of Tennessee",
                "Texas U.S. Circuit for (all) District(s) of Texas",
                "Vermont U.S. Circuit for the District of Vermont",
                "Virginia U.S. Circuit for (all) District(s) of Virginia",
                "West Virginia U.S. Circuit for (all) District(s) of West Virginia",
                "Wisconsin U.S. Circuit for (all) District(s) of Wisconsin",
                "Wyoming U.S. Circuit for the District of Wyoming",
                "Circuit Court of the District of Columbia",
                "Nebraska U.S. Circuit for the District of Nebraska",
                "Colorado U.S. Circuit for the District of Colorado",
                "Washington U.S. Circuit for (all) District(s) of Washington",
                "Idaho U.S. Circuit Court for (all) District(s) of Idaho",
                "Montana U.S. Circuit Court for (all) District(s) of Montana",
                "Utah U.S. Circuit Court for (all) District(s) of Utah",
                "South Dakota U.S. Circuit Court for (all) District(s) of South Dakota",
                "North Dakota U.S. Circuit Court for (all) District(s) of North Dakota",
                "Oklahoma U.S. Circuit Court for (all) District(s) of Oklahoma",
                "Court of Private Land Claims"] 
                
cert_labels = ["case did not arise on cert or cert not granted",
               "federal court conflict",
               "federal court conflict and to resolve important or significant question",
               "putative conflict",
               "conflict between federal court and state court",
               "state court conflict",
               "federal court confusion or uncertainty",
               "state court confusion or uncertainty",
               "federal court and state court confusion or uncertainty",
               "to resolve important or significant question",
               "to resolve question presented",
               "no reason given",
               "other reason"]
               
disposition_labels = ['stay, petition, or motion granted',
                      'affirmed',
                      'reversed',
                      'reversed and remanded',
                      'vacated and remanded',
                      'affirmed and reversed (or vacated) in part',
                      'affirmed and reversed (or vacated) in part and remanded',
                      'vacated',
                      'petition denied or appeal dismissed',
                      'modify',
                      'remand',
                      'unusual disposition']
                      
direction_labels = ['conservative', 'liberal', 'unspecifiable']

decision_kind = ["opinion of the court (orally argued)",
                 "per curiam (no oral argument)",
                 "decrees",
                 "equally divided vote",
                 "per curiam (orally argued)",
                 "judgment of the Court (orally argued)",
                 "seriatim"]